---
date: 2020/03/10 15:45:02
title: SQLAlchemy 1.3.14 Released
author: Mike B
---

SQLAlchemy release 1.3.14 is now available.

Release 1.3.14 includes a wide variety of bugfixes in most areas.  Notable
changes include a rework of how internal exceptions are raised, such that
under Python 3 all exceptions that are "chained" to another internal exception
should have a "cause" linked, to avoid misleading stack traces.   The new
feature has been tested that it does not create new reference cycles as is a
common issue with Python 3 exception objects, however users should report
any regressions encountered on the GitHub issue tracker.

See the changelog for descriptions of all bug fixes.

As is the case with all releases, we'd like to thank all the contributors who
helped with this release.

Changelog for 1.3.14 is at `Changelog </changelog/CHANGES_1_3_14>`_.

SQLAlchemy 1.3.14 is available on the `Download Page </download.html>`_.
